<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType><TargetFramework>net8.0</TargetFramework>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <LangVersion>9.0</LangVersion>
  </PropertyGroup>
  <ItemGroup><Compile Include="Program.cs"/><Compile Include="../../Assets/Scripts/Graph/PdbStructure.cs"/></ItemGroup>
<ItemGroup><None Include="Fixtures/4INS.pdb" CopyToOutputDirectory="PreserveNewest" /></ItemGroup></Project>
